[package]
name = "typesafe-builders-derive"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = "2.0.13"
