name: Rust

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rust Version Info
      run: |
        cargo version
        rustc --version
        cargo clippy --version

    - name: Format
      run: cargo fmt --all -- --check

    - uses: actions-rs/cargo@v1
      name: Build
      with:
        command: build
        args: --locked --release --all-targets --all-features

    - uses: actions-rs/cargo@v1
      name: Test
      with:
        command: test
        args: --locked --release --all-targets no --all-features

    - uses: actions-rs/cargo@v1
      name: Clippy
      with:
        command: clippy
        args: --locked --release --all-targets --all-features -- -D warnings

    - uses: actions-rs/cargo@v1
      name: Documentation
      with:
        command: doc
        args: --locked --release --no-deps --all-features

    - uses: actions-rs/cargo@v1
      name: Doc Test
      with:
        command: test
        args: --locked --release --doc
